/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "udp.h"
/* Header for class cn_etsoft_smarthome_jniUtils */

#ifndef _Included_cn_etsoft_smarthome_jniUtils
#define _Included_cn_etsoft_smarthome_jniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_etsoft_smarthome_jniUtils
 * Method:    udpServer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_etsoft_smarthome_jniUtils_udpServer
  (JNIEnv *env, jclass obj) {

    udp_server();
}

#ifdef __cplusplus
}
#endif
#endif
